version: "3.9"

services:
  test:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "4000:4000"
    volumes:
      - test:/test
    command: >
      npm run serve

volumes:
  test:
