version: "3.9"

services:
  robotframework:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "4200:4200"
    volumes:
      - robotframework:/test
    command: >
      npm run serve
    networks:
      - network

networks:
  network:
    driver: bridge
    name: network

volumes:
  robotframework:
