version: "3.9"

services:
  test-react:
    container_name: 'test-react'
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "4000:4000"
    volumes:
      - test-react:/test
    command: >
      npm run serve

volumes:
  test-react:
