---
name: Checks

on:
  push:
    branches:
      - 'gantt'

jobs:
  test-lint:
    name: Test and Lint
    runs-on: ubuntu-latest
    steps:
      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USER }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Run actions/checkout@v2
        uses: actions/checkout@v2
      - name: Build the docker-compose stack
        run: docker-compose -f docker-compose.yml up -d
      - name: Run Test
        run: docker-compose -f docker-compose.yml run --rm robotframework sh -c "robot -d result testcases/login.robot"

